name: update-docker-description

on:
  push:
    branches:
      - master

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
    - name: Update repo description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: thomaslandro/website-monitor
